
info_teksti1 = "Hi!"
info_teksti2 = "I didn't make this game for example to put it to Steam or to get money from it."
info_teksti3 = "I made it only for studying purposes. I didn't aim to get perfect and fully ready game at any point."
info_teksti4 = "At the beginin I had two goals:"
info_teksti5 = "My first and biggest goal was to learn how to use pygame and python in general."
info_teksti6 = "And if I'm being honest I think I did great job with that."
info_teksti7 = "Then the second goal was to build a game which might be fun to play."
info_teksti8 = "When I'm writing this I really find the game fun to play though it isn't anything complicated."
info_teksti9 = "-------------------------------------------------------------------------------------------------------"
info_teksti10 = "Oki, now let's head to the info section:"
info_teksti11 = "                                                                                                       "
info_teksti12 = "                                                                                                       "
info_teksti13 = "                                                                                                       "
info_teksti14 = "RTDWD (aka Roll the dice with death) is a game where the idea is to chose from two glasses."
info_teksti15 = "One of the glasses is equal to death: when player chooses the wrong glass the game ends and player dies."

